### PR TITLE
Add optional version_id param to S3 signer

### PR DESCRIPTION
**Pull request by mschout**
This allows generating signed links for specific versions of objects in
a bucket with versioning enabled

### CODE REVIEW

**Comment by mschout** [comment]
If you need more context here, this is already in the AWS Java SDK...

**Comment by pplu** [comment]
Thanks for this! No problem in having this functionality :)

Would you mind explaining the function of `x!!` in `(versionId => $self->version_id) x!! $self->version_id`. I understand what you're doing (I tend to use `(defined ...) ? (xxx => yyy) : ()`), but I'd like to know how it works.

**Comment by mschout** [comment]
Its the "Enterprise" operator.  See https://metacpan.org/dist/perlsecret/view/lib/perlsecret.pod#Enterprise

**Comment by mschout** [comment]
That said, if you prefer defined ternary op, I have no objections to that.

**Comment by pplu** [comment]
Just uploaded 0.06 to CPAN with your changes

> That said, if you prefer defined ternary op, I have no objections to that.

I have no objections of having an Enterprise in the code :)

**Comment by pplu** [comment]
Thanks for your contribution

**Pull request merged**
